project_id = "sqhikfqygphnemptxvoo"

[functions.generate-itinerary]
verify_jwt = true

[functions.get-mapbox-token]
verify_jwt = true

[functions.generate-trip-suggestions]
verify_jwt = true

[functions.demo-login]
verify_jwt = false

[functions.search-flights]
verify_jwt = false
